baseURL: '/'
languageCode: id-ID
title: My personal blog
summaryLength: 10

# this isrequired so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
    page: /:slug
    blog: /:slug
    private: /:slug

