baseURL: '/'
params:
  author: Miftahus Surur
  description: Di sosial media, kita bisa menjadi siapa saja
  tagline: My Personal Blog
title: Miftahus Surur
summaryLength: 10
paginate: 4

# setting default language
languageCode: id-ID
defaultContentLanguage: id
defaultContentLang: id

# this isrequired so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
    page: /:slug
    blog: /:slug
    private: /:slug

taxonomies:
  category: categories
  tag: tags

# for automation get date
enableGitInfo: true

frontmatter:
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate

enableEmoji: true

disableLiveReload: false
