baseURL: '/'
languageCode: id-ID
title: My personal blog
summaryLength: 10

# this isrequired so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
    page: /:slug
    blog: /:slug
    private: /:slug

# for automation get date
enableGitInfo : true

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: false
  tdewolff:
    css:
      keepCSS2: true
      precision: 0
    html:
      keepComments: false
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: false
      keepWhitespace: true
    js:
      keepVarNames: false
      precision: 0
    json:
      keepNumbers: false
      precision: 0
    svg:
      precision: 0
    xml:
      keepWhitespace: false
